language: node_js
sudo: false
node_js:
  - '4'
  - '6'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-react-webpack-alt' ]; then cd .. && eval "mv $currentfolder generator-react-webpack-alt" && cd generator-react-webpack-alt; fi
after_success: 'npm run coverage'
